In [1]:
import numpy as np

#  Creating ndarrays
## 1. np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

In [4]:
data1 = [1, 2, 3, 4, 5]
np.array(data1)

array([1, 2, 3, 4, 5])

In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
np.array(data2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## 2. np.zeros(shape, dtype=float, order='C')     与之类似有np.ones()、np.empty()

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
np.empty((2, 3, 2))

array([[[1.40824633e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.74136024e-057]],

       [[3.69983105e-057, 6.81924389e-038],
        [1.67473778e-076, 6.17154485e-062],
        [1.45265921e-051, 3.63977601e+175]]])

## 3. np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [46]:
np.eye(3, 4, -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

## 4. np.arange([start,] stop[, step,], dtype=None)

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

## 5. np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [25]:
np.linspace(0, np.pi, 100)

array([0.        , 0.03173326, 0.06346652, 0.09519978, 0.12693304,
       0.1586663 , 0.19039955, 0.22213281, 0.25386607, 0.28559933,
       0.31733259, 0.34906585, 0.38079911, 0.41253237, 0.44426563,
       0.47599889, 0.50773215, 0.53946541, 0.57119866, 0.60293192,
       0.63466518, 0.66639844, 0.6981317 , 0.72986496, 0.76159822,
       0.79333148, 0.82506474, 0.856798  , 0.88853126, 0.92026451,
       0.95199777, 0.98373103, 1.01546429, 1.04719755, 1.07893081,
       1.11066407, 1.14239733, 1.17413059, 1.20586385, 1.23759711,
       1.26933037, 1.30106362, 1.33279688, 1.36453014, 1.3962634 ,
       1.42799666, 1.45972992, 1.49146318, 1.52319644, 1.5549297 ,
       1.58666296, 1.61839622, 1.65012947, 1.68186273, 1.71359599,
       1.74532925, 1.77706251, 1.80879577, 1.84052903, 1.87226229,
       1.90399555, 1.93572881, 1.96746207, 1.99919533, 2.03092858,
       2.06266184, 2.0943951 , 2.12612836, 2.15786162, 2.18959488,
       2.22132814, 2.2530614 , 2.28479466, 2.31652792, 2.34826

# Type cast -->a.astype()

![](https://img-blog.csdnimg.cn/20190805151404846.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzMwNzQ4ODYz,size_16,color_FFFFFF,t_70)

## 1. int --> float

In [28]:
a = np.arange(5)
print(a, a.dtype, sep='\n')
b = a.astype(np.float)
print(b, b.dtype, sep='\n')

[0 1 2 3 4]
int32
[0. 1. 2. 3. 4.]
float64


## 2. float --> int, (decimal part will be truncated)

In [29]:
a = np.array([1.2, 2.5, 3.9, 6.4])
print(a, a.dtype, sep='\n')
b = a.astype(np.int)
print(b, b.dtype, sep='\n')

[1.2 2.5 3.9 6.4]
float64
[1 2 3 6]
int32


## 3. str --> num

In [39]:
a = np.array(['1.23', '4.5', '100', '-9.6'], dtype=np.string_)
print(a, a.dtype, sep='\n')
b = a.astype(np.float)
print(b, b.dtype, sep='\n')

[b'1.23' b'4.5' b'100' b'-9.6']
|S4
[  1.23   4.5  100.    -9.6 ]
float64


# Arithmetic with NumPy Arrays

## 1. +, -, *, /, **, %, **

In [49]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [50]:
a + 10

array([10, 11, 12, 13, 14])

In [51]:
a - 4

array([-4, -3, -2, -1,  0])

In [52]:
a * 2

array([0, 2, 4, 6, 8])

In [53]:
a / 5

array([0. , 0.2, 0.4, 0.6, 0.8])

In [54]:
a % 3

array([0, 1, 2, 0, 1], dtype=int32)

In [55]:
a ** 2

array([ 0,  1,  4,  9, 16], dtype=int32)

## 2. >, <, ==, >=, <=, !=

In [68]:
a , b = np.random.random((2, 3)), np.random.random((2, 3))
print('a:', a, sep='\n')
print('b:', b, sep='\n')

a:
[[0.75044481 0.43571073 0.17576022]
 [0.08508236 0.90212141 0.47073929]]
b:
[[0.1653514  0.30195994 0.46305522]
 [0.61877302 0.94406292 0.4185715 ]]


In [69]:
a > b

array([[ True,  True, False],
       [False, False,  True]])

In [70]:
a == b

array([[False, False, False],
       [False, False, False]])

In [71]:
a < b

array([[False, False,  True],
       [ True,  True, False]])

In [72]:
a >= b

array([[ True,  True, False],
       [False, False,  True]])

In [73]:
a != b

array([[ True,  True,  True],
       [ True,  True,  True]])

# Basic Indexing and Slicing

In [90]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 1. accessing value

In [92]:
print(a[5])
print(a[5:8])
print(a[:3])
print(a[:-3])

5
[5 6 7]
[0 1 2]
[0 1 2 3 4 5 6]


In [98]:
print(b[0], b[:2], b[1][2], b[1,2], b[:2, 1:], sep='\n----------\n')

[1 2 3]
----------
[[1 2 3]
 [4 5 6]]
----------
6
----------
6
----------
[[2 3]
 [5 6]]


## 2. modifying value

In [99]:
a[5:8] = 12
a

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [100]:
b[0] = 10
b

array([[10, 10, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [101]:
b[:, -1] = -1
b

array([[10, 10, -1],
       [ 4,  5, -1],
       [ 7,  8, -1]])

## 3. boolean indexing

In [102]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [103]:
names == 'Will'

array([False, False,  True, False,  True, False, False])

In [105]:
names[names == 'Will']

array(['Will', 'Will'], dtype='<U4')

In [107]:
data = np.random.random((7, 4))
data

array([[0.59028618, 0.08474988, 0.24642917, 0.99727839],
       [0.75122645, 0.46784203, 0.3779746 , 0.42856805],
       [0.65852845, 0.57268485, 0.46720685, 0.87345267],
       [0.22115235, 0.87378715, 0.61703166, 0.15248516],
       [0.91096314, 0.45710725, 0.77829319, 0.92000196],
       [0.24557961, 0.7046679 , 0.4506215 , 0.40183276],
       [0.0980379 , 0.46017913, 0.05821307, 0.98181751]])

In [108]:
data[names == 'Bob']

array([[0.59028618, 0.08474988, 0.24642917, 0.99727839],
       [0.22115235, 0.87378715, 0.61703166, 0.15248516]])

In [109]:
data[data < 0.5]

array([0.08474988, 0.24642917, 0.46784203, 0.3779746 , 0.42856805,
       0.46720685, 0.22115235, 0.15248516, 0.45710725, 0.24557961,
       0.4506215 , 0.40183276, 0.0980379 , 0.46017913, 0.05821307])

In [111]:
data[data > 0.5] = 10
data

array([[10.        ,  0.08474988,  0.24642917, 10.        ],
       [10.        ,  0.46784203,  0.3779746 ,  0.42856805],
       [10.        , 10.        ,  0.46720685, 10.        ],
       [ 0.22115235, 10.        , 10.        ,  0.15248516],
       [10.        ,  0.45710725, 10.        , 10.        ],
       [ 0.24557961, 10.        ,  0.4506215 ,  0.40183276],
       [ 0.0980379 ,  0.46017913,  0.05821307, 10.        ]])

## 4. fancy indexing