# 这100道练习，带你玩转Numpy

参考自https://www.kesci.com/home/project/59f29f67c5f3f5119527a2cc

## 1. 导入numpy库

In [1]:
import numpy as np

## 2. 打印numpy的版本和配置说明

In [2]:
print(np.__version__)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kevin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/kevin/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kevin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

## 3. 创建一个长度为10的空向量

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4.  如何找到任何一个数组的内存大小？

In [4]:
Z = np.zeros(10)
print(f'{Z.size * Z.itemsize} bytes')

80 bytes


## 5. 如何从命令行得到numpy中add函数的说明文档?

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

## 6. 创建一个长度为10并且除了第五个值为1的空向量

In [6]:
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 7. 创建一个值域范围从10到49的向量

In [7]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 8. 反转一个向量

In [8]:
Z = np.arange(10)
Z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 9. 创建一个 3x3 并且值从0到8的矩阵

In [9]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 

In [10]:
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4], dtype=int64),)

## 11. 创建一个 3x3 的单位矩阵

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 12. 创建一个 3x3x3的随机数组

In [12]:
np.random.random((3, 3, 3))

array([[[0.28675329, 0.8307883 , 0.2088464 ],
        [0.53516066, 0.37870939, 0.96319793],
        [0.19694683, 0.88261374, 0.92730922]],

       [[0.76788129, 0.97099708, 0.6516392 ],
        [0.81220777, 0.18110675, 0.14429877],
        [0.31178058, 0.31090942, 0.18153495]],

       [[0.11790352, 0.59227881, 0.05713833],
        [0.5128794 , 0.39904786, 0.68622939],
        [0.45091409, 0.78095786, 0.03840181]]])

## 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值 

In [13]:
Z = np.random.random((10, 10))
print(Z)
print(Z.min(), Z.max())

[[0.79425616 0.59206845 0.33072405 0.43386504 0.97194419 0.28012937
  0.70710823 0.28672639 0.26205863 0.53547377]
 [0.03350543 0.25978554 0.99964718 0.05331593 0.02249447 0.30520697
  0.67489226 0.76892396 0.94187326 0.05973582]
 [0.98146993 0.29149463 0.96239043 0.52404953 0.9842527  0.05107919
  0.49019564 0.67467338 0.08509922 0.11226781]
 [0.54054865 0.99615402 0.22698636 0.3871091  0.7652671  0.88810477
  0.14932017 0.35955574 0.59817682 0.63086768]
 [0.50793361 0.90890765 0.11887489 0.26356875 0.15051504 0.66034551
  0.66770773 0.04705606 0.92445409 0.66190747]
 [0.64733297 0.54511937 0.92649916 0.01130881 0.04145749 0.7222137
  0.18887082 0.42048346 0.63199329 0.09064556]
 [0.42840942 0.91598264 0.8233169  0.70754472 0.96422133 0.67326431
  0.24908643 0.63122246 0.68869458 0.6954671 ]
 [0.37861288 0.63038873 0.28642744 0.90039448 0.60552885 0.09442745
  0.44497605 0.24800837 0.6659125  0.0630723 ]
 [0.63225024 0.10334864 0.07944334 0.04598369 0.41586637 0.13815744
  0.16176838 

## 14. 创建一个长度为30的随机向量并找到它的平均值

In [14]:
Z = np.random.random(30)
Z.mean()

0.49734463575096854

## 15.  创建一个二维数组，其中边界值为1，其余值为0

In [16]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 16. 对于一个存在在数组，如何添加一个用0填充的边界

In [18]:
Z = np.ones((5, 5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## 17.  以下表达式运行的结果分别是什么? 

0 * np.nan  
np.nan == np.nan  
np.inf > np.nan  
np.nan - np.nan  
0.3 == 3 * 0.1  

In [20]:
print(
     0*np.nan, 
     np.nan == np.nan,
     np.inf > np.nan,
     np.nan - np.nan,
     0.3 == 3 * 0.1,
     sep='\n'
     )

nan
False
False
nan
False


## 18.  创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 

In [21]:
np.diag(1 + np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## 19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [24]:
Z = np.zeros((8, 8))
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [25]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

## 21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [27]:
np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## 22.  对一个5x5的随机矩阵做归一化

In [28]:
Z = np.random.random((5, 5))
print(Z)
Zmin, Zmax = Z.min(), Z.max()
Z = (Z - Zmin)/(Zmax-Zmin)
Z

[[0.04561987 0.89884212 0.08838466 0.5271022  0.48552405]
 [0.67708381 0.16973855 0.03645263 0.50124018 0.94035739]
 [0.19992772 0.02413194 0.4970781  0.81212255 0.60309573]
 [0.19960163 0.03261167 0.5688723  0.70371135 0.92544766]
 [0.06406769 0.40163222 0.56187892 0.22064349 0.68088066]]


array([[0.02345267, 0.9546888 , 0.07012763, 0.54895906, 0.50357923],
       [0.71265415, 0.15892007, 0.01344723, 0.52073236, 1.        ],
       [0.19186957, 0.        , 0.51618972, 0.86004008, 0.63190102],
       [0.19151367, 0.00925507, 0.59454839, 0.74171636, 0.98372701],
       [0.04358726, 0.4120168 , 0.58691557, 0.21447947, 0.71679816]])

## 23.  创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？

In [30]:
color = np.dtype([('r', np.ubyte, 1),
               ('g', np.ubyte, 1),
               ('b', np.ubyte, 1),
               ('a', np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

## 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ 

In [32]:
a = np.ones((5, 3))
b = np.ones((3, 2))
print(a @ b)
print('-'*10)
print(np.dot(a, b))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
----------
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## 25.  给定一个一维数组，对其在3到8之间的所有元素取反 

In [33]:
Z = np.arange(11)
Z[(Z >= 3) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

## 26.  下面脚本运行后的结果是什么?

In [38]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5),-1))

10
10


## 27. 考虑一个整数向量Z,下列表达合法的是哪个?

```
Z**Z  
2 << Z >> 2  
Z <- Z  
1j * Z  
Z / 1 / 1  
Z < Z > Z
```

In [42]:
Z = np.arange(5)
print(Z ** Z,
      2 << Z >> 2,
      Z < -Z,
      1j * Z,
      Z / 1 / 1,
      sep='\n------------------------\n')
print(Z < Z > Z)

[  1   1   4  27 256]
------------------------
[0 1 2 4 8]
------------------------
[False False False False False]
------------------------
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
------------------------
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## 28. 下列表达式的结果分别是什么?

```
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [43]:
print(
    np.array(0) / np.array(0),
    np.array(0) // np.array(0),
    np.array([np.nan]).astype(int).astype(float),
    sep='\n-----------------\n')

nan
-----------------
0
-----------------
[-2.14748365e+09]


C:\Users\kevin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\kevin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


## 29. 如何从零位对浮点数组做舍入 ?

In [44]:
Z = np.random.uniform(-10,+10,10)
print(Z)
np.copysign(np.ceil(np.abs(Z)), Z)

[-0.25404528 -0.50179426 -9.20461844 -8.15172113  8.7693163   7.58421339
  5.43580106 -9.94452228 -1.07056457  3.62172927]


array([ -1.,  -1., -10.,  -9.,   9.,   8.,   6., -10.,  -2.,   4.])

## 30. 如何找到两个数组中的共同元素?

In [45]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1, Z2, sep='\n-----------\n')
print(np.intersect1d(Z1,Z2))

[0 1 8 5 9 9 8 8 6 2]
-----------
[9 3 5 8 7 0 9 3 2 0]
[0 2 5 8 9]


## 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)?

In [49]:
# 1. Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# 2. An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

## 32.  下面的表达式是正确的吗?

```
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [50]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

## 33. 如何得到昨天，今天，明天的日期? 

In [51]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-05
Today is 2019-08-06
Tomorrow is 2019-08-07


## 34. 如何得到所有与2016年7月对应的日期？ 

In [52]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

## 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [61]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(A, B, C, sep='\n---------------\n')

[1. 1. 1.]
---------------
[2. 2. 2.]
---------------
[3. 3. 3.]


In [62]:
np.add(A,B,out=B)
print(A, B, sep='\n---------------\n')

[1. 1. 1.]
---------------
[3. 3. 3.]


In [63]:
np.negative(A,out=A)
print(A)

[-1. -1. -1.]


In [64]:
np.multiply(A,B,out=A)
print(A, B, sep='\n---------\n')

[-3. -3. -3.]
---------
[3. 3. 3.]


## 36. 用五种不同的方法去提取一个随机数组的整数部分

In [66]:
Z = np.random.uniform(0,10,10)
Z

array([9.32611242, 5.32837056, 4.95431229, 4.48251834, 8.03166777,
       7.28968639, 8.82639162, 4.31915663, 7.42670832, 9.06349999])

In [67]:
print (
    Z - Z%1,
    np.floor(Z),
    np.ceil(Z)-1,
    Z.astype(int),
    np.trunc(Z),
    sep='\n-----------\n')

[9. 5. 4. 4. 8. 7. 8. 4. 7. 9.]
-----------
[9. 5. 4. 4. 8. 7. 8. 4. 7. 9.]
-----------
[9. 5. 4. 4. 8. 7. 8. 4. 7. 9.]
-----------
[9 5 4 4 8 7 8 4 7 9]
-----------
[9. 5. 4. 4. 8. 7. 8. 4. 7. 9.]


## 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4

In [68]:
Z = np.zeros((5,5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

## 38. 通过考虑一个可生成10个整数的函数，来构建一个数组

In [69]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [70]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## 40. 创建一个长度为10的随机向量，并将其排序 

In [74]:
Z = np.random.random(10)
print(Z)
Z.sort()
Z

[0.56995092 0.29243459 0.54744172 0.54944531 0.9891943  0.29165963
 0.45257293 0.25554421 0.88948795 0.98842533]


array([0.25554421, 0.29165963, 0.29243459, 0.45257293, 0.54744172,
       0.54944531, 0.56995092, 0.88948795, 0.98842533, 0.9891943 ])

## 41. 对于一个小数组，如何用比 np.sum更快的方式对其求和？

In [75]:
Z = np.arange(10)
np.add.reduce(Z)

45

## 42.  对于两个随机数组A和B，检查它们是否相等

In [76]:
# 方法一：
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [77]:
# 方法二：
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False


## 43. 创建一个只读数组(read-only) 

In [78]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

## 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [79]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.81799627 0.33667128 0.43260933 0.8184934  1.01923592 0.77665189
 0.5153675  0.7314646  0.96147503 0.9441204 ]
[1.25098636 0.31723764 0.71864906 0.40966466 1.21011074 0.33121633
 0.04792891 0.70415528 1.34255845 0.07569589]


## 45. 创建一个长度为10的向量，并将向量中最大值替换为1

In [82]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 1
Z

[0.62565541 0.69855293 0.12872092 0.50684751 0.98640328 0.02039825
 0.03615205 0.15785943 0.49642724 0.30551341]


array([0.62565541, 0.69855293, 0.12872092, 0.50684751, 1.        ,
       0.02039825, 0.03615205, 0.15785943, 0.49642724, 0.30551341])

## 46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域

In [83]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

## 47. 给定两个数组X和Y，构造Cauchy矩阵C (C<sub>ij</sub> =1/(x<sub>i</sub> - y<sub>j</sub>))

In [84]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


## 48. 打印每个numpy标量类型的最小值和最大值？

In [85]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
print('-'*30)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
------------------------------
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


## 49. 如何打印一个数组中的所有数值?

In [89]:
np.set_printoptions(threshold=np.iinfo(int).max)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 50. 给定标量时，如何找到数组中最接近标量的值？

In [92]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
print (Z[index])

40.130833754379836
40
